name: balancer

services:
  nginx:
    image: "nginx:1.27.5-alpine-slim"
    container_name: nginx
    environment:
      NGINX_ENTRYPOINT_LOCAL_RESOLVERS: yes
    volumes:
      - ${NGINX_CONFIG_DIR}:/etc/nginx/templates
      - ${SSL_CERTS_DIR}:/app/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - devnet

networks:
  devnet:
    name: devnet