name: ${PROJECT_NAME}

services:
  django:
    domainname: ${PROJECT_NAME}-django
    image: ${PROJECT_NAME}-django
    container_name: ${PROJECT_NAME}-django
    build:
      context: ${PROJECT_DIR}/backend
    env_file:
      - ${PROJECT_DIR}/environment/env.base
      - ${PROJECT_DIR}/environment/env.dev
    volumes:
      - ${PROJECT_DIR}/backend:/app/src
      - ${PROJECT_DIR}/idp_certs:/app/saml_idp_certs
    depends_on:
      - postgres
    networks:
      - app
      - devnet

  nextjs:
    image: ${PROJECT_NAME}-nextjs
    container_name: ${PROJECT_NAME}-nextjs
    domainname: ${PROJECT_NAME}-nextjs
    build:
      context: ${PROJECT_DIR}/spa
    env_file:
      - ${PROJECT_DIR}/environment/env.base
      - ${PROJECT_DIR}/environment/env.dev
    volumes:
      - ${PROJECT_DIR}/spa/app:/app/app
      - ${PROJECT_DIR}/spa/next_utils:/app/next_utils
      - ${PROJECT_DIR}/spa/api:/app/api
      - ${PROJECT_DIR}/spa/components:/app/components
      - ${PROJECT_DIR}/spa/.eslintrc.js:/app/.eslintrc.js
      - ${PROJECT_DIR}/spa/instrumentation.ts:/app/instrumentation.ts
      - ${PROJECT_DIR}/spa/next-end.d.ts:/app/next-end.d.ts
      - ${PROJECT_DIR}/spa/next.config.mjs:/app/next.config.mjs
      - ${PROJECT_DIR}/spa/tsconfig.json:/app/tsconfig.json
      - ${PROJECT_DIR}/spa/sentry.client.config.ts:/app/sentry.client.config.ts
      - ${PROJECT_DIR}/spa/sentry.server.config.ts:/app/sentry.server.config.ts
      - ${PROJECT_DIR}/spa/sentry.edge.config.ts:/app/sentry.edge.config.ts
      - ${PROJECT_DIR}/spa/package.json:/app/package.json
    networks:
      - app
      - devnet

  minio:
    command: server /data --console-address ":9001"
    image: "minio/minio:latest"
    container_name: ${PROJECT_NAME}-minio
    domainname: ${PROJECT_NAME}-minio
    environment:
      MINIO_ROOT_USER: minio_${PROJECT_NAME}
      MINIO_ROOT_PASSWORD: minio_${PROJECT_NAME}
    volumes:
      - minio-data:/data
    networks:
      - app
      - devnet


  postgres:
    image: "postgres:16.4-alpine"
    container_name: ${PROJECT_NAME}-postgres
    domainname: ${PROJECT_NAME}-postgres
    environment:
      POSTGRES_PASSWORD: ${PROJECT_NAME}
      POSTGRES_USER: ${PROJECT_NAME}
      POSTGRES_DB: ${PROJECT_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app

  celery:
    image: ${PROJECT_NAME}-django
    domainname: ${PROJECT_NAME}-celery
    container_name: ${PROJECT_NAME}-celery
    command: celery --app application.celeryapp worker -E -l info
    volumes:
      - ${PROJECT_DIR}/backend:/app/src
    env_file:
      - ${PROJECT_DIR}/environment/env.base
      - ${PROJECT_DIR}/environment/env.dev
    networks:
      - app
      - devnet
    profiles:
      - celery

  centrifugo:
    image: "centrifugo/centrifugo:v5.4.9"
    container_name: ${PROJECT_NAME}-centrifugo
    domainname: ${PROJECT_NAME}-centrifugo
    volumes:
      - ${PROJECT_DIR}/dev-scripts/centrifugo.json.dev:/centrifugo/centrifugo.json
    command: centrifugo -c centrifugo.json --engine=redis
    depends_on:
      - redis
    networks:
      - app
      - devnet
    profiles:
      - centrifugo

  redis:
    image: "redis:7.2.3"
    container_name: ${PROJECT_NAME}-redis
    domainname: ${PROJECT_NAME}-redis
    volumes:
      - redis-data:/data
    networks:
      - app
      - devnet
    profiles:
      - celery
      - centrifugo


volumes:
  postgres-data:
    driver: local
    name: ${PROJECT_NAME}-postgres-data
  minio-data:
    driver: local
    name: ${PROJECT_NAME}-minio-data
  redis-data:
    driver: local
    name: ${PROJECT_NAME}-redis-data


networks:
  app:
    name: ${PROJECT_NAME}
  devnet:
    name: devnet
    external: true